### PR TITLE
20-incident-factory

### LINKED ISSUE #16: Incident Factory
### Feature Description
Create `Factories/IncidentFactory.cs` to fulfill the following requirements:
* Instantiate as singleton
* Store `ActiveIncident` on the instance
* Get a single incident (by IncidentId) from the database
* Get all incidents from the database

* Instantiate as singleton
```
// Make the factory a singleton to maintain state across all uses
		private static IncidentFactory _instance;
		public static IncidentFactory Instance
		{
			get {
				if (_instance == null) {
					_instance = new IncidentFactory ();
				}
				return _instance;
			}
		}
```

* Store `ActiveIncident` on the instance
```
// To track the currently active incident - selected by user
		private Incident _activeIncident = null;
		public Incident ActiveIncident {
			get {
				return _activeIncident;
			}
			set{ 
				_activeIncident = value;
			}
		}
```

* Get a single incident (by IncidentId) from the database
```
// Get a single incident
		public Incident get(int IncidentId)
		{
			BangazonConnection conn = new BangazonConnection ();
			Incident i = null;

			conn.execute (@"select 
				IncidentId,
				IncidentTypeId,
				OrderId,
				EmployeeId,
				Resolution,
				DateResolved
				from Incident
				where IncidentId = " + IncidentId, (SqliteDataReader reader) => {
				while (reader.Read ())
				{
					i = new Incident {
						IncidentId = reader.GetInt32(0),
						IncidentTypeId = reader.GetInt32(1),
						OrderId = reader.GetInt32(2),
						EmployeeId = reader.GetInt32(3),
						Resolution = reader [4].ToString(),
						DateResolved = reader [5].ToString()
					};
				}
			});

			return i;
		}
```

* Get all incidents from the database
```
// Get all incidents
		public List<Incident> getAll() 
		{
			BangazonConnection conn = new BangazonConnection ();
			List<Incident> list = new List<Incident> ();

			// Execute the query to retrieve all incidents
			conn.execute (@"select 
				IncidentId,
				IncidentTypeId,
				OrderId,
				EmployeeId,
				Resolution,
				DateResolved
				from Incident", 
				(SqliteDataReader reader) => {
					while (reader.Read ())
					{
						list.Add(new Incident {
						          IncidentId = reader.GetInt32(0),
						          IncidentTypeId = reader.GetInt32(1),
						          OrderId = reader.GetInt32(2),
						          EmployeeId = reader.GetInt32(3),
						          Resolution = reader [4].ToString(),
						          DateResolved = reader [5].ToString()
						});
					}
				}
			);
                        return list;
               }
```

### PR DESCRIPTION
**Pull request by MattKraatz**
## Status
**READY**

## Testing

[X] I have added passing tests for all new functionality.

[X] I have confirmed that all test prior to this pull request still PASS.

## Documentation

[X] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[ ] This PR does **NOT** require documentation.

## Description
Create an IncidentFactory with methods to retrieve a single Incident or a list of all Incidents.

## Resolves Issue Number
Resolves #16 

## Deploy Notes

```sh
git pull --prune
git checkout 20-incident-factory
dotnet test
```

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

1. Make sure the program builds and all tests pass on your machine

## Impacted Files in Application
List general components of the application that this PR will affect:

* Factories/IncidentFactory.cs
* IncidentFactoryTests.cs

### CODE REVIEW

**Comment by garrett-vangilder** [comment]
🎺 🎺 🎺 LGTM

**Comment by matthamil** [comment]
LGTM 📯

**Review by Anulfo — COMMENTED** [review]
LGTM

**Review by Anulfo — APPROVED** [review]
Team Charles Approved! LGTU

**Pull request merged**
