### PR TITLE
fixed LabelFactory.cs GetLabels to return based on int passed

### PR DESCRIPTION
**Pull request by daynewright**
## Status
**READY**

## Testing

[X] I have added passing tests for all new functionality.

[X] I have confirmed that all test prior to this pull request still PASS.

## Documentation

[ ] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[X] This PR does **NOT** require documentation.

## Description
Fixed GetLabel query to return based on incidentId passed in.

## Resolves Issue Number
#39 

## Deploy Notes

```sh
git pull --prune
git checkout 39-label-factory-bug)
```

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

1.  Run and check that all tests pass
2. 🚀 LEVEL UP:  Run query from GetLabels() on DB in DB Browser and test

## Impacted Files in Application
List general components of the application that this PR will affect:

* LabelFactory.cs

### CODE REVIEW

**Comment by matthamil** [comment]
LGTM :burrito:

**Comment by garrett-vangilder** [comment]
LGTM

**Review by MattKraatz — APPROVED** [review]
LGTM 👍

**Comment by Anulfo** [comment]
LGTM

**Pull request merged**
