### PR TITLE
12-login-action :: User can now log in.

### PR DESCRIPTION
**Pull request by matthamil**
## Status
**READY**

## Testing

[X] I have added passing tests for all new functionality.

[X] I have confirmed that all test prior to this pull request still PASS.

## Documentation

[X] I have fully documented features in this PR's code. Please put an `X` in the box to confirm.

[ ] This PR does **NOT** require documentation.

## Description
Users can now log in. If a user enters "new user", the user can create a new employee account, and it will login as that user.

## Resolves Issue Number

https://github.com/TeamCharles/customer-service/issues/12

## Deploy Notes

```sh
git pull --prune
git checkout 12-login-action
dotnet test  # while inside the test directory
```

## Steps to Test or Reproduce

1. Add `using customer_service.Actions` to the top of `Program.cs`

1. Add `LoginAction.ReadInput()` to your `Main()` method.

1. Attempt to log in as an Employee.

1. Run the program again. Try creating a new employee through the menu.

1. Enjoy!

## Impacted Files in Application

* Actions/LoginAction.cs

* Factories/EmployeeFactory.cs

* Tests/EmployeeFactoryTests.cs

### CODE REVIEW

**Comment by matthamil** [comment]
@TeamCharles/team Ready for review

**Review by Anulfo — COMMENTED** [review]
LGTM

**Review by Anulfo — APPROVED** [review]

**Review by MattKraatz — APPROVED** [review]
That was a tough one, nice work!

**Comment by daynewright** [comment]
LGTM!

**Comment by garrett-vangilder** [comment]
LGTM

**Pull request merged**
